### ISSUE TITLE
Seems it doesn't work under Expo... unfortunatly

### ISSUE THREAD

**Issue by LC92** [songsterq/react-native-pdf-thumbnail#19]
Running  the example when code arrives to
const { uri, width, height } = await PdfThumbnail.generate(filePath, page); 
results  an error ' [TypeError: null is not an object (evaluating '_reactNativePdfThumbnail.default.generate')]'

I guess this is because I'm using expo. Any possibility to make it works within Expo?

**Comment by oberruti** [comment]
It's not working without Expo either. Please, could you check it?

**Comment by songsterq** [comment]
I don't think native modules can work in Expo Go. You can try Expo EAS, see #37.
