### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-pdf-thumbnail":

### ISSUE THREAD

**Issue by Ritesh175862** [songsterq/react-native-pdf-thumbnail#2]
![Uploading Screenshot 2020-09-23 at 12.33.07 PM.png…]()

**Comment by williamsilveira45** [comment]
Same....

**Comment by tandonpushkar** [comment]
same..

**Comment by Sangram8897** [comment]
Please resolve

**Comment by songsterq** [comment]
How do I repro this? @Ritesh175862 can you provide the screenshot again, it was not uploaded successfully.

**Comment by ManhVuTien** [comment]
platform :ios, '11.0' import it in `Podfile`

**Comment by songsterq** [comment]
Please try release 1.1.0.
