### ISSUE TITLE
how to get thumbnail using pass http pdf url in PdfThumbnail.generate?

### ISSUE THREAD

**Issue by suresh03** [songsterq/react-native-pdf-thumbnail#27]
Pleae anyone help me this

**Comment by junaidanjum** [comment]
[https://github.com/songsterq/react-native-pdf-thumbnail/issues/7#issuecomment-809686805](url)

**Comment by OrataroSunsoftapp** [comment]
Same

**Comment by Manasseh-Ankrah** [comment]
Having the same challenge here.

Please has anyone found a solution for this?

**Comment by songsterq** [comment]
You should download the file and use a local uri instead. I don't want to include additional dependencies for downloading.
