### ISSUE TITLE
Warning on iOS - requires main queue setup

### ISSUE THREAD

**Issue by mlecoq** [songsterq/react-native-pdf-thumbnail#3]
I have the following warning after starting my app on iOS:

```Module PdfThumbnail requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.```

**Comment by songsterq** [comment]
Released in https://github.com/songsterq/react-native-pdf-thumbnail/releases/tag/v1.0.2.
