### ISSUE TITLE
Error on generating thumbnail for the file returned by react native document picker 

### ISSUE THREAD

**Issue by DDushkin** [songsterq/react-native-pdf-thumbnail#36]
Hello, I use `react-native-document-picker` to get the file URI and then pass trying to get the thumbnail like in the example 
```ts
const { uri } = await PdfThumbnail.generate(filePath, 0);
```
But in the end I see such error

```js
[DocumentManager] Failed to associate thumbnails for picked URL
...
{Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}
```

**Comment by songsterq** [comment]
Where are you picking the file from? I checked the error message it seems to be something with iCloud drive.

**Comment by songsterq** [comment]
Closing for lack of update.
