### ISSUE TITLE
Placeholder in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jameswilddev** [songsterq/react-native-pdf-thumbnail#38]
> Enforcement
>
> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at **[INSERT CONTACT METHOD]**. All complaints will be reviewed and investigated promptly and fairly.
>
> All community leaders are obligated to respect the privacy and security of the reporter of any incident.

**Comment by songsterq** [comment]
Fixed with ede6ced67fe638a67a8af34195f725faed454090, thanks!
