### ISSUE TITLE
Error while generating PDF

### ISSUE THREAD

**Issue by mattpilleul** [songsterq/react-native-pdf-thumbnail#43]
Hello everyone ! 

I'm currently working on a React Native Chat app, and trying to implement pdf upload. To display the pdf, this library was perfectly fitting.

When I try to render the PDF thumbnail, I'm getting the following error : 
`Error: File file:///xxxx.... not found`

On first render while sending the chat everything seems to work fine, but when leaving chat and opening it again, I get this error.

Could we try and find a solution. Thanks

**Comment by songsterq** [comment]
The output file is stored in temp directory, so you may want to copy it to more persistent storage.
