### ISSUE TITLE
Release IPHONEOS_DEPLOYMENT_TARGET updates

### ISSUE THREAD

**Issue by PixoDev** [songsterq/react-native-pdf-thumbnail#49]
Hey,

I saw that a change was introduced in this commit updating the IPHONEOS_DEPLOYMENT_TARGET, however seems like version 1.2.0 is still using IPHONEOS_DEPLOYMENT_TARGET=8.0
https://github.com/songsterq/react-native-pdf-thumbnail/commit/c34888957105bb82985539a35c7391c36b57c28d

Is possible to release 1.2.1 version with this changes? right now im manually patching it every time 

Thanks!

**Comment by songsterq** [comment]
Done!
