### ISSUE TITLE
Not generating thumbnail from URI (from link)

### ISSUE THREAD

**Issue by vaibhavgadekar** [songsterq/react-native-pdf-thumbnail#7]
I am not able to  generate thumbnail from URI (from link)
example (**http://www.africau.edu/images/default/sample.pdf**)

**code**
`const { uri, width, height } = await PdfThumbnail.generate("http://www.africau.edu/images/default/sample.pdf", 0);`

**Comment by songsterq** [comment]
On [Android](https://github.com/songsterq/react-native-pdf-thumbnail/blob/master/android/src/main/java/com/songsterq/reactnative/PdfThumbnailModule.kt#L77) it doesn't support `http` uri scheme.
On [iOS](https://github.com/songsterq/react-native-pdf-thumbnail/blob/master/ios/PdfThumbnail.swift#L54) I haven't tested whether it is supported.

I think you can download the file first, then use the local file path to get thumbnail.

**Comment by songsterq** [comment]
Closing as we don't want to add dependency to download files. Your app can download the file first and use the local file path to get thumbnail.
